/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'snark' at '7/18/15 11:30 AM' with Gradle 2.5
 *
 * @author snark, @date 7/18/15 11:30 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
